"""Build an offline annotation form for the fixed random evaluation sample."""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent

def main():
    corpus = {r['doc_id']: r for r in map(json.loads, (ROOT/'corpus.jsonl').read_text().splitlines())}
    labels = list(map(json.loads, (ROOT/'human_labels.jsonl').read_text().splitlines()))
    sample = json.loads((ROOT/'evaluation_sample.json').read_text())
    taxonomy = json.loads((ROOT/'taxonomy.json').read_text())
    payload = {'records': [corpus[r['doc_id']] for r in labels], 'labels': labels,
               'fields': taxonomy['fields'], 'fingerprint': sample['corpus_sha256'] + sample['fields_sha256'] + '-human-reviewed-v1'}
    template = r'''<!doctype html>
<html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<title>Shreya | Pharma corpus annotation</title>
<style>
*{box-sizing:border-box}body{margin:0;background:#f3f5f8;color:#13233b;font:15px/1.5 system-ui,sans-serif}header{background:#13233b;color:white;padding:22px 30px}h1{font-size:25px;margin:0}header p{margin:5px 0 0;color:#cbd5e1}.toolbar{padding:14px 25px;background:white;border-bottom:1px solid #d9e0e7;display:flex;gap:10px;align-items:center;flex-wrap:wrap;position:sticky;top:0;z-index:2}button,.import{background:#006c70;color:white;border:0;border-radius:5px;padding:10px 14px;cursor:pointer;font:inherit}button.secondary,.import{background:#e8eef3;color:#13233b}select,input,textarea{font:inherit;padding:9px;border:1px solid #aebac8;border-radius:4px;background:white;max-width:100%}main{display:grid;grid-template-columns:1fr 1fr;gap:22px;padding:24px;max-width:1600px;margin:auto}section{background:white;padding:24px;border:1px solid #dde3e9;border-radius:8px;min-width:0}h2{font-size:20px;margin-top:0}h3{font-size:15px;color:#006c70}.source{white-space:pre-wrap;font:14px/1.7 system-ui,sans-serif;overflow-wrap:anywhere}.source-table{font:13px/1.6 monospace;white-space:pre-wrap;overflow-wrap:anywhere;background:#f3f5f8;padding:12px}label.field{display:block;font-weight:650;margin-top:20px}small{display:block;color:#536273;margin:4px 0 8px}textarea,input[type=text],.field+small+select{width:100%}textarea{min-height:110px}#status{margin-left:auto;font-weight:600}#message{padding:0 25px;color:#9e3d08}.check{display:flex;gap:10px;margin-top:22px;padding:15px;background:#edf7f4}.note{background:#fff5df;padding:12px;border-radius:4px}a{color:#006c70}footer{padding:20px 25px} @media(max-width:850px){main{grid-template-columns:1fr}.toolbar{position:static}}
</style>
<header><h1>Pharma job corpus · Reference-label review</h1><p>Shreya · 25 randomly selected postings · Seed 820 · Full source text</p></header>
<div class="toolbar"><button id="prev" class="secondary">Previous</button><select id="jump" aria-label="Select posting"></select><button id="next" class="secondary">Next</button><button id="download">Download human_labels.jsonl</button><label class="import">Import saved labels<input type="file" id="import" accept=".jsonl,.txt" hidden></label><span id="status"></span></div>
<p id="message" role="status"></p>
<main><section><h2 id="title"></h2><p><a id="url" target="_blank" rel="noopener">Original posting</a></p><h3>Original structured fields</h3><pre class="source-table" id="table"></pre><h3>Complete description</h3><div class="source" id="text"></div></section>
<section><h2>Your labels</h2><p class="note">Review every field against the complete source. Enter one complete source sentence or bullet per line for list fields. An empty list means nothing is stated; it is valid only after you review the posting.</p><label class="field" for="annotator">Annotator</label><input type="text" id="annotator" placeholder="Your name"><div id="fields"></div><label class="check"><input type="checkbox" id="complete"><span>I personally reviewed this posting and completed every field.</span></label><p>See ANNOTATION_GUIDE.md for rules on alternatives, preferred qualifications, and work arrangement.</p></section></main>
<footer>Progress is saved in this browser when local storage is available. Download a backup before closing. This file works offline and sends no annotation data anywhere.</footer>
<script id="payload" type="application/json">__PAYLOAD__</script>
<script>
const data=JSON.parse(document.getElementById('payload').textContent); let rows=data.labels,index=0;
const key='pharma-human-labels-'+data.fingerprint, el=id=>document.getElementById(id);
try{let saved=JSON.parse(localStorage.getItem(key));if(saved&&saved.length===rows.length&&saved.every((r,i)=>r.doc_id===rows[i].doc_id))rows=saved}catch(e){}
function message(s){el('message').textContent=s}
function persist(){try{localStorage.setItem(key,JSON.stringify(rows))}catch(e){message('Browser storage unavailable. Download labels to preserve progress.')}updateStatus()}
function updateStatus(){el('status').textContent=rows.filter(r=>r.annotation_status==='complete').length+' / '+rows.length+' annotations complete';[...el('jump').options].forEach((o,i)=>{o.textContent=(i+1)+'. '+(rows[i].annotation_status==='complete'?'✓ ':'')+data.records[i].table_json.job_title})}
function collect(){const row=rows[index]; row.annotator=el('annotator').value.trim(); row.human_reviewed=el('complete').checked; row.annotation_origin='human'; for(const [name,spec] of Object.entries(data.fields)){const v=el('f_'+name).value;row.human_label[name]=spec.kind==='list'?v.split('\n').map(s=>s.trim()).filter(Boolean):v}row.annotation_status=el('complete').checked?'complete':'pending';persist()}
function show(){const r=data.records[index],row=rows[index];el('title').textContent=r.table_json.job_title;el('url').href=r.source_url;el('table').textContent=JSON.stringify(r.table_json,null,2);el('text').textContent=r.raw_text;el('jump').value=index;el('annotator').value=row.annotator||'';el('fields').replaceChildren();for(const [name,spec] of Object.entries(data.fields)){let l=document.createElement('label');l.className='field';l.htmlFor='f_'+name;l.textContent=name.replaceAll('_',' ');let help=document.createElement('small');help.textContent=spec.description;let input;if(spec.values){input=document.createElement('select');let o=document.createElement('option');o.value='';o.textContent='Choose a value';input.append(o);spec.values.forEach(v=>{let o=document.createElement('option');o.value=v;o.textContent=v;input.append(o)})}else{input=document.createElement(spec.kind==='list'?'textarea':'input');if(spec.kind!=='list')input.type='text'}input.id='f_'+name;input.value=spec.kind==='list'?(row.human_label[name]||[]).join('\n'):(row.human_label[name]||'');input.addEventListener('input',()=>{el('complete').checked=false;collect()});el('fields').append(l,help,input)}el('complete').checked=row.human_reviewed===true;updateStatus()}
data.records.forEach((r,i)=>{let o=document.createElement('option');o.value=i;el('jump').append(o)});
el('jump').onchange=()=>{collect();index=Number(el('jump').value);show()};el('prev').onclick=()=>{collect();index=Math.max(0,index-1);show()};el('next').onclick=()=>{collect();index=Math.min(rows.length-1,index+1);show()};
el('annotator').oninput=collect;el('complete').onchange=()=>{collect();if(el('complete').checked){let r=rows[index];let missing=Object.entries(data.fields).filter(([n,s])=>s.kind!=='list'&&!r.human_label[n]);if(!r.annotator||missing.length){el('complete').checked=false;collect();message('Enter your name and all text/category fields before marking complete.')}else message('Posting marked complete.')}};
el('download').onclick=()=>{collect();const blob=new Blob([rows.map(r=>JSON.stringify({doc_id:r.doc_id,human_label:r.human_label,annotation_status:r.annotation_status,annotation_origin:r.annotation_origin,annotator:r.annotator,human_reviewed:r.human_reviewed===true})).join('\n')+'\n'],{type:'application/x-ndjson'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='human_labels.jsonl';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);message('Save this download over assignment1/human_labels.jsonl. Pending records will block model evaluation.')};
el('import').onchange=async e=>{try{const content=await e.target.files[0].text();const incoming=content.trim().split(/\r?\n/).map(JSON.parse);if(incoming.length!==rows.length||new Set(incoming.map(r=>r.doc_id)).size!==rows.length)throw Error('Expected the same 25 unique sample IDs.');const byId=Object.fromEntries(incoming.map(r=>[r.doc_id,r]));if(rows.some(r=>!byId[r.doc_id]))throw Error('Sample IDs do not match.');for(const r of incoming){if(!r.human_label||typeof r.human_label!=='object')throw Error('Missing label object.');for(const [n,s] of Object.entries(data.fields)){const v=r.human_label[n];if(s.kind==='list'?(!Array.isArray(v)||v.some(x=>typeof x!=='string')):typeof v!=='string')throw Error('Invalid field '+n);if(s.values&&v&&!s.values.includes(v))throw Error('Invalid category '+n)}}rows=rows.map(r=>byId[r.doc_id]);persist();show();message('Imported saved labels.')}catch(e){message('Import failed: '+e.message)}};show();
</script></html>'''
    (ROOT/'label_review.html').write_text(template.replace('__PAYLOAD__',json.dumps(payload,ensure_ascii=False).replace('<','\\u003c')),encoding='utf-8')
    print('Wrote label_review.html')

if __name__ == '__main__': main()
